import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import IDE from './IDE';
import Loader from './Loader';
import About from './About';
import Action from './Action';
import Divider from './Divider';
import Team from './Team';
import Footer from './Footer';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
ReactDOM.render(<Loader />, document.getElementById('loader'));
ReactDOM.render(<IDE />, document.getElementById('ide'));
ReactDOM.render(<Action />, document.getElementById('action'));
ReactDOM.render(<About />, document.getElementById('about'));
ReactDOM.render(<Divider />, document.getElementById('divider'));
ReactDOM.render(<Divider />, document.getElementById('divider'));
ReactDOM.render(<Team />, document.getElementById('team'));
ReactDOM.render(<Footer />, document.getElementById('footer'));
registerServiceWorker();
